"""Add trip models and trip_images table

Revision ID: 55b923e82ba0
Revises: ce2d1d9afb8d
Create Date: 2026-01-23 19:47:56.501026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b923e82ba0'
down_revision: Union[str, Sequence[str], None] = 'ce2d1d9afb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
